const { execFileSync } = require('node:child_process')
const { mkdirSync, readFileSync, writeFileSync } = require('node:fs')
const { dirname, join, resolve } = require('node:path')

const PROJECT_ROOT = resolve(__dirname, '..')
const GENERATED_VERSION_FILE = join(
  PROJECT_ROOT,
  'src',
  'shared',
  'generated-version.ts'
)
const GENERATED_TAURI_VERSION_FILE = join(
  PROJECT_ROOT,
  'src-tauri',
  'tauri.version.conf.json'
)

function readBaseVersion(projectRoot = PROJECT_ROOT) {
  const packageJson = JSON.parse(
    readFileSync(join(projectRoot, 'package.json'), 'utf8')
  )
  const match = /^(\d+)\.(\d+)\.(\d+)(?:[-+].*)?$/.exec(packageJson.version)
  if (!match) {
    throw new Error('package.json version must use A.B.C semantic version format')
  }
  return { major: Number(match[1]), minor: Number(match[2]) }
}

function readBuildNumber(projectRoot = PROJECT_ROOT) {
  const override = process.env.OLLAMA_PROFILER_BUILD_NUMBER
  if (override !== undefined) {
    if (!/^\d+$/.test(override)) {
      throw new Error('OLLAMA_PROFILER_BUILD_NUMBER must be a non-negative integer')
    }
    return Number(override)
  }
  try {
    const output = execFileSync('git', ['rev-list', '--count', 'HEAD'], {
      cwd: projectRoot,
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore']
    }).trim()
    return /^\d+$/.test(output) ? Number(output) : 0
  } catch {
    return 0
  }
}

function getAppVersion(projectRoot = PROJECT_ROOT) {
  const { major, minor } = readBaseVersion(projectRoot)
  return `${major}.${minor}.${readBuildNumber(projectRoot)}`
}

function writeGeneratedVersion(projectRoot = PROJECT_ROOT) {
  const version = getAppVersion(projectRoot)
  const target =
    projectRoot === PROJECT_ROOT
      ? GENERATED_VERSION_FILE
      : join(projectRoot, 'src', 'shared', 'generated-version.ts')
  const contents = [
    '// Generated by scripts/version.cjs. Do not edit or commit.',
    `export const APP_VERSION = '${version}'`,
    ''
  ].join('\n')
  mkdirSync(dirname(target), { recursive: true })
  let existing
  try {
    existing = readFileSync(target, 'utf8')
  } catch {
    existing = undefined
  }
  if (existing !== contents) writeFileSync(target, contents, 'utf8')

  const tauriTarget =
    projectRoot === PROJECT_ROOT
      ? GENERATED_TAURI_VERSION_FILE
      : join(projectRoot, 'src-tauri', 'tauri.version.conf.json')
  const tauriContents = `${JSON.stringify({ version }, null, 2)}\n`
  mkdirSync(dirname(tauriTarget), { recursive: true })
  let existingTauri
  try {
    existingTauri = readFileSync(tauriTarget, 'utf8')
  } catch {
    existingTauri = undefined
  }
  if (existingTauri !== tauriContents) {
    writeFileSync(tauriTarget, tauriContents, 'utf8')
  }
  return version
}

function checkTag(tag, projectRoot = PROJECT_ROOT) {
  const expected = `v${getAppVersion(projectRoot)}`
  if (tag !== expected) {
    throw new Error(`Release tag ${tag || '(missing)'} must equal ${expected}`)
  }
  return expected
}

if (require.main === module) {
  try {
    const args = process.argv.slice(2)
    if (args[0] === '--write') {
      process.stdout.write(`${writeGeneratedVersion()}\n`)
    } else if (args[0] === '--check-tag') {
      process.stdout.write(`${checkTag(args[1] || process.env.GITHUB_REF_NAME)}\n`)
    } else {
      process.stdout.write(`${getAppVersion()}\n`)
    }
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`)
    process.exitCode = 1
  }
}

module.exports = {
  checkTag,
  getAppVersion,
  readBaseVersion,
  readBuildNumber,
  writeGeneratedVersion
}
